version: '2.4'

services:

  elasticsearch:
    image: "${ELASTIC_DOCKER_REPO:-docker.elastic.co/elasticsearch/elasticsearch}:5.6.3"
    container_name: elasticsearch
    volumes:
      - ${ELASTIC_VOLUME_CONF_FILE:-../volumes/elasticsearch/conf/elasticsearch.yml}:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "${ELASTIC_HTTP_PORT:-9200}:9200"
      - "${ELASTIC_BINARY_PORT:-9300}:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    labels:
      - "stack_name=${STACK_NAME:-<STACK_NAME>}"
