services:
  fake-smtp:
    container_name: "${CONTAINER_NAME_PREFIX}fake-smtp"
    image: "${FAKE_SMTP_DOCKER_REPO:-munkyboy/fakesmtp}"
    ports:
      - "2525:25"
    volumes:
      - type: volume
        source: fake-smtp_mail
        target: /var/mail
    labels:
      - "stack_name=${STACK_NAME:-<STACK_NAME>}"
volumes:
  fake-smtp_mail:
