#Runs an HBase instance with its required zookeeper
version: '2.4'

services: 

  hbase:
    container_name: hbase
    image: "${STROOM_STATS_HBASE_DOCKER_REPO:-gchq/stroom-stats-hbase}:${STROOM_STATS_TAG:-v0.6-LATEST}_hbase-v2.1"
    hostname: "${HBASE_HOST:-hbase}"
    #The optimal solution here would be to specify '["./wait-for-it_busybox.sh", "${ZOOKEEPER_QUORUM:-zookeeper:2181}", "--"]
    #in entrypoint then let the command from the docker file be tacked on the end, however if you override entrypoint
    #compose will wipe out the dockerfile's command.  Thus it all needs to be decalred here
    command: ["./wait-for-it_busybox.sh", "${ZOOKEEPER_QUORUM:-zookeeper:2181}", "--", "/entrypoint.sh"]
    environment:
      - HBASE_MANAGES_ZK=false
    ports:
      #- 8080:8080
      #- 8085:8085
      #- 9090:9090
      #- 9095:9095
      - 16000:16000
      - 16010:16010
      - 16020:16020
      - 16201:16201
      - 16301:16301
      - 60000:60000
      - 60010:60010
      - 60020:60020
      - 60030:60030
    labels:
      - "stack_name=${STACK_NAME:-<STACK_NAME>}"
