#Runs an HDFS instance
services:
  hdfs:
    image: "${HADOOP_DOCKER_REPO:-sequenceiq/hadoop-docker}:${HDFS_TAG:-2.7.1}"
    container_name: hdfs
    hostname: hdfs
    command: ["/etc/bootstrap.sh", "-d"]
    ports:
      - 9000:9000
      - 8020:8020
      - 50010:50010
    labels:
      - "stack_name=${STACK_NAME:-<STACK_NAME>}"
