services:
  stroom-all-dbs:
    image: "${MYSQL_DOCKER_REPO:-mysql}:${MYSQL_TAG:-8.4.3}"
    container_name: "${CONTAINER_NAME_PREFIX}stroom-all-dbs"
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${STROOM_DB_ROOT_PASSWORD:-my-secret-pw}
        # The following env vars are used to substitute values in
        # 001_create_databases.sql.template

        # Database names
      - STROOM_STATS_DB_NAME=${STROOM_STATS_DB_NAME:-stats}
      - STROOM_DB_NAME=${STROOM_DB_NAME:-stroom}

        # Database users
      - STROOM_STATS_DB_USERNAME=${STROOM_STATS_DB_USERNAME:-statsuser}
      - STROOM_DB_USERNAME=${STROOM_DB_USERNAME:-stroomuser}

        # Database passwords
      - STROOM_STATS_DB_PASSWORD=${STROOM_STATS_DB_PASSWORD:-stroompassword1}
      - STROOM_DB_PASSWORD=${STROOM_DB_PASSWORD:-stroompassword1}

    cap_add:
      - SYS_NICE  # CAP_SYS_NICE added to get rid of `mbind: Operation not permitted` messages.

    # We need to increase default ulimits to allow a maximum of 1000 concurrent connections.
    ulimits:
      nofile:
        soft: 20000
        hard: 40000

    volumes:
        # Note this is a bind mount on a file so will bind to the inode of the file, not the name
      - ${MYSQL_VOLUME_CONF_FILE:-../volumes/stroom-all-dbs/conf/stroom-all-dbs.cnf}:/etc/mysql/conf.d/stroom-all-dbs.cnf:ro
      - ${MYSQL_VOLUME_INIT:-../volumes/stroom-all-dbs/init}:/docker-entrypoint-initdb.d:ro
      - type: volume
        source: stroom-all-dbs_data
        target: /var/lib/mysql
      - type: volume
        source: stroom-all-dbs_logs
        target: /var/log/mysql
    logging:
      driver: "json-file"
      options:
        max-size: "${MYSQL_STD_OUT_LOGS_MAX_SIZE:-10m}"
        max-file: "${MYSQL_STD_OUT_LOGS_MAX_FILES:-2}"
    labels:
      - "stack_name=${STACK_NAME:-<STACK_NAME>}"
volumes:
  stroom-all-dbs_data:
  stroom-all-dbs_logs:
