services:
  stroom-stats:
    container_name: "${CONTAINER_NAME_PREFIX}stroom-stats"
    image: "${STROOM_STATS_DOCKER_REPO:-gchq/stroom-stats}:${STROOM_STATS_TAG:-v0.6-LATEST}"
    environment:
      - DOCKER_HOST_HOSTNAME=${DOCKER_HOST_HOSTNAME:-UNKNOWN}
      - DOCKER_HOST_IP=${DOCKER_HOST_IP:-UNKNOWN}
      - JAVA_OPTS=${STROOM_STATS_JAVA_OPTS:- -Xms50m -Xmx1024m --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=10768,suspend=n }
      # At the moment, stroom-stats gets it document entities from the stroom DB, not the 'stats' DB.
      # The 'stats' DB contains legacy SQL stats tables only
      - STATS_DB_USER=${STROOM_DB_USERNAME:-stroomuser}
      - STATS_DB_PASSWORD=${STROOM_DB_PASSWORD:-stroompassword1}
      - STATS_DB_URL=jdbc:mysql://${STROOM_DB_HOST:-$DB_HOST_IP}:${STROOM_DB_PORT:-3307}/${STROOM_DB_NAME:-stroom}?useUnicode=yes&characterEncoding=UTF-8
      # quorum string of the form along the lines of
      # host1:2181
      # host1:2181/myChRoot
      # host1:2181,host2:2181,host3:2181
      # host1:2181,host2:2181,host3:2181/myChRoot
      - STATS_ZK_QUORUM=${ZOOKEEPER_QUORUM:-zookeeper:2181}

      # The following env vars set the values used to seed an empty zookeeper.
      # Once ZK has been seeded, changing these values has no affect as stroom-stats
      # will always use the values obtained from ZK.
      # Changing the value in ZK requires the ZK CLI or some other tool.
      #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      - STATS_KAFKA_BOOTSTRAP=${STATS_KAFKA_BOOTSTRAP:-kafka:9092}
      # Comma delimited list of hosts in the ZK quorum (no port or chroot), e.g. host1,host2,host3
      - STATS_HBASE_ZK_QUORUM_HOSTS=${HBASE_ZOOKEEPER_QUORUM_HOSTS:-zookeeper}
      - ADMIN_CONTEXT_PATH=/statsAdmin
      - AUTHENTICATION_SERVICE_URL=http://${NGINX_ADVERTISED_HOST:-$HOST_IP}/api/auth
        # TODO Not sure if the above line should be:
      #- STROOM_AUTH_AUTHENTICATION_SERVICE_URL=http://${NGINX_ADVERTISED_HOST:-$HOST_IP}/authenticationService/v1
      - AUTHORISATION_SERVICE_URL=http://${NGINX_ADVERTISED_HOST:-$HOST_IP}/api/authorisation/v1
      - STROOM_STATS_ADVERTISED_HOST_OR_IP=${STROOM_STATS_ADVERTISED_HOST_OR_IP:-$HOST_IP}
    ports:
      - "${STROOM_STATS_APP_PORT:-8086}:8086"
      - "${STROOM_STATS_ADMIN_PORT:-8087}:8087"
      - "${STROOM_STATS_DEBUG_PORT:-10768}:10768"
    logging:
      driver: "json-file"
      options:
        max-size: "${STROOM_STATS_STD_OUT_LOGS_MAX_SIZE:-10m}"
        max-file: "${STROOM_STATS_STD_OUT_LOGS_MAX_FILES:-2}"
    labels:
      - "stack_name=${STACK_NAME:-<STACK_NAME>}"
volumes:
  stroom-stats_logs:
