services:
  stroom-annotations-service:
    container_name: "${CONTAINER_NAME_PREFIX}stroom-annotations-service"
    image: "${STROOM_ANNOTATIONS_SERVICE_DOCKER_REPO:-gchq/stroom-annotations-service}:${STROOM_ANNOTATIONS_SERVICE_TAG:-v0.2.1-alpha.1}"
    environment:
      - DB_USER=${STROOM_ANNOTATIONS_DB_USERNAME:-annotationsuser}
      - DB_PASSWORD=${STROOM_ANNOTATIONS_DB_PASSWORD:-stroompassword1}
      - DB_URL=jdbc:mysql://${STROOM_ANNOTATIONS_DB_HOST:-$HOST_IP}:${STROOM_ANNOTATIONS_DB_PORT:-3307}/${STROOM_ANNOTATIONS_DB_NAME:-annotations}
      - ADMIN_CONTEXT_PATH=/annotationsServiceAdmin
      - AUTH_UI=${STROOM_AUTH_UI_ACTIVE_SCHEME:-https}://${STROOM_AUTH_UI_HOST:-$HOST_IP}:${STROOM_AUTH_UI_ACTIVE_PORT:-5000}/login
      - JWS_MINUTES_UNTIL_EXPIRATION_FOR_USER_TOKEN=43200 # 43200 minutes = 30 days
      - JWS_MINUTES_UNTIL_EXPIRATION_FOR_API_TOKEN=525600 # 525600 minutes = 1 year
      - JWS_MINUTES_UNTIL_EXPIRATION_FOR_EMAIL_RESET_TOKEN=5 # Only 5 minutes
      - AUTHORISATION_SERVICE_URL=https://${NGINX_ADVERTISED_HOST:-$HOST_IP}/authorisationService/v1
      - AUTHORISATION_SERVICE_IS_AUTHORISED_PATH=/isAuthorised
    ports:
      - 8199:8199
      - 8200:8200
    entrypoint: ./wait-for-it_busybox.sh ${STROOM_ANNOTATIONS_DB_HOST:-$HOST_IP}:${STROOM_ANNOTATIONS_DB_PORT:-3307} -- java -jar stroom-annotations-service-all.jar server config.yml
    labels:
      - "stack_name=${STACK_NAME:-<STACK_NAME>}"
