services:
  stroom-proxy-5:
    container_name: "${CONTAINER_NAME_PREFIX}stroom-proxy-5"
    image: "${STROOM_PROXY_DOCKER_REPO:-gchq/stroom-proxy}:${STROOM_PROXY_TAG:-v5.1-LATEST}"
    ports:
      - 8090:8080
    volumes:
      - type: volume
        source: stroom-proxy-5-local_config
        target: /stroom-proxy/config
      - type: volume
        source: stroom-proxy-5-local_content
        target: /stroom-proxy/content
      - type: volume
        source: stroom-proxy-5-local_logs
        target: /stroom-proxy/logs
      - type: volume
        source: stroom-proxy-5-local_repo
        target: /stroom-proxy/repo
    logging:
      driver: "json-file"
      options:
        max-size: "${STROOM_PROXY_STD_OUT_LOGS_MAX_SIZE:-10m}"
        max-file: "${STROOM_PROXY_STD_OUT_LOGS_MAX_FILES:-2}"
    labels:
      - "stack_name=${STACK_NAME:-<STACK_NAME>}"
volumes:
  stroom-proxy-5-local_config:
  stroom-proxy-5-local_content:
  stroom-proxy-5-local_logs:
  stroom-proxy-5-local_repo:
