version: '2.1'

services:

  stroom-auth-ui:
    container_name: stroom-auth-ui
    image: "${STROOM_AUTH_UI_DOCKER_REPO:-gchq/stroom-auth-ui}:${STROOM_AUTH_UI_TAG:-v0.1-LATEST}"
    # All URLs are accessed from a browser, and so need to refer to the advertised host.
    environment:
      - AUTH_UI_AUTHENTICATION_SERVICE_URL=http://${STROOM_AUTH_SERVICE_HOST:-stroom-auth-service}/authService/authentication/v1
      - AUTH_UI_USER_SERVICE_URL=http://${STROOM_AUTH_SERVICE_HOST:-stroom-auth-service}/authService/user/v1
      - AUTH_UI_TOKEN_SERVICE_URL=http://${STROOM_AUTH_SERVICE_HOST:-stroom-auth-service}/authService/token/v1
      - AUTH_UI_AUTHORISATION_SERVICE_URL=http://${STROOM_AUTHORISATION_SERVICE_HOST:-stroom}:8080/api/authorisation/v1
      - AUTH_UI_STROOM_UI_URL=http://${STROOM_HOST:-stroom}:8080/stroom
      - AUTH_UI_ADVERTISED_URL=http://${STROOM_AUTH_UI_HOST:-stroom-auth-ui}:5000
      - AUTH_UI_APP_CLIENT_ID=stroom-accounts
    ports:
      - 5000:5000
