version: '2.4'

services:

  stroom-proxy-local:
    container_name: stroom-proxy-local
    image: "${STROOM_PROXY_DOCKER_REPO:-gchq/stroom-proxy}:${STROOM_PROXY_TAG:-v7-LATEST}"
    environment:
      - DOCKER_HOST_HOSTNAME=${DOCKER_HOST_HOSTNAME:-UNKNOWN}
      - DOCKER_HOST_IP=${DOCKER_HOST_IP:-UNKNOWN}
      - FORWARDING_ENABLED=${STROOM_PROXY_LOCAL_FORWARDING_ENABLED:-true}
      - FORWARDING_HOST_VERIFICATION_ENABLED=${STROOM_PROXY_LOCAL_FORWARDING_HOST_VERIFICATION_ENABLED:-true}
      - FORWARD_URL=${STROOM_PROXY_LOCAL_FORWARD_URL:-https://nginx/stroom/datafeeddirect}
      - JAVA_OPTS=${STROOM_PROXY_LOCAL_JAVA_OPTS:- -Xms50m -Xmx2g --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED}
      - STORING_ENABLED=${STROOM_PROXY_LOCAL_STORING_ENABLED:-true}
      - FEED_STATUS_URL=${STROOM_PROXY_LOCAL_FEED_STATUS_URL:-https://nginx/api/feedStatus/v1}
      - IDENTITY_PROVIDER_TYPE=${STROOM_PROXY_LOCAL_IDENTITY_PROVIDER_TYPE:-NO_IDP}
      - REST_CLIENT_VERIFY_HOSTNAME=${STROOM_PROXY_LOCAL_REST_CLIENT_VERIFY_HOSTNAME:-true}
    ports:
      # Allow the ports on the docker host to be chaned, internally they are fixed
      - "${STROOM_PROXY_LOCAL_APP_PORT:-8090}:8090"
      - "${STROOM_PROXY_LOCAL_ADMIN_PORT:-8091}:8091"
      #- "${STROOM_PROXY_LOCAL_DEBUG_PORT:-10766}:10766"
    healthcheck:
      test: curl --connect-timeout 5 --max-time 10 --fail --silent --head --output /dev/null http://localhost:8091/proxyAdmin/healthcheck || exit 1
      start_period: 30s
      interval: 1m
      timeout: 5s
      retries: 3
    volumes:
      - ${STROOM_PROXY_LOCAL_VOLUME_CERTS:-../volumes/stroom-proxy-local/certs}:/stroom-proxy/certs:ro
      - ${STROOM_PROXY_LOCAL_VOLUME_CONFIG:-../volumes/stroom-proxy-local/config}:/stroom-proxy/config:ro
      - type: volume
        source: stroom-proxy-local_content
        target: /stroom-proxy/content
        # This volume is shared with stroom. If we ever want to run stroom without
        # a local proxy then we need to move this out into in override yml as is done with
        # stroom-log-sender
      - type: volume
        source: stroom-proxy-local_logs
        target: /stroom-proxy/logs
      - type: volume
        source: stroom-proxy-local_repo
        target: /stroom-proxy/repo
      - type: volume
        source: stroom-proxy-local_db
        target: /stroom-proxy/db
      - type: volume
        source: stroom-proxy-local_failures
        target: /stroom-proxy/failures
    tmpfs:
      - "/tmp:size=${STROOM_PROXY_LOCAL_TEMP_MOUNT_SIZE:-8g}"
        # Sqlite-jdbc places a transient library file here on boot and needs exec perms on
      - "/stroom-proxy/sqlite_library:exec"
    logging:
      driver: "json-file"
      options:
        max-size: "${STROOM_PROXY_LOCAL_STD_OUT_LOGS_MAX_SIZE:-10m}"
        max-file: "${STROOM_PROXY_LOCAL_STD_OUT_LOGS_MAX_FILES:-2}"
    labels:
      - "stack_name=${STACK_NAME:-<STACK_NAME>}"
volumes:
  stroom-proxy-local_content:
  stroom-proxy-local_logs:
  stroom-proxy-local_repo:
  stroom-proxy-local_db:
  stroom-proxy-local_failures:
