version: '2.4'

services: 

  stroom-all-dbs:
    # NB: stroom-auth uses a MySQL testcontainer (https://www.testcontainers.org/). This allows the 
    # integration tests to run without an external database, i.e. without stroom-resources. 
    # But this does mean that if you change the MySQL version _here_ you should also change it _there_:
    # https://github.com/gchq/stroom-auth/blob/master/stroom-auth-svc/src/integration-test/java/stroom/auth/service/resources/support/Database_IT.java#L35
    image: "${MYSQL_DOCKER_REPO:-mysql}:${MYSQL_TAG:-5.6.47}"
    container_name: stroom-all-dbs
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${STROOM_DB_ROOT_PASSWORD:-my-secret-pw}
        # The following env vars are used to substitute values in
        # 001_create_databases.sql.template

        # Database names
      - STROOM_ANNOTATIONS_DB_NAME=${STROOM_ANNOTATIONS_DB_NAME:-annotations}
      - STROOM_AUTH_DB_NAME=${STROOM_AUTH_DB_NAME:-auth}
      - STROOM_CONFIG_DB_NAME=${STROOM_CONFIG_DB_NAME:-config}
      - STROOM_DATAMETA_DB_NAME=${STROOM_DATAMETA_DB_NAME:-datameta}
      - STROOM_EXPLORER_DB_NAME=${STROOM_EXPLORER_DB_NAME:-explorer}
      - STROOM_PROCESS_DB_NAME=${STROOM_PROCESS_DB_NAME:-process}
      - STROOM_STATS_DB_NAME=${STROOM_STATS_DB_NAME:-stats}
      - STROOM_DB_NAME=${STROOM_DB_NAME:-stroom}

        # Database users
      - STROOM_ANNOTATIONS_DB_USERNAME=${STROOM_ANNOTATIONS_DB_USERNAME:-annotationsuser}
      - STROOM_AUTH_DB_USERNAME=${STROOM_AUTH_DB_USERNAME:-authuser}
      - STROOM_CONFIG_DB_USERNAME=${STROOM_CONFIG_DB_USERNAME:-configuser}
      - STROOM_DATAMETA_DB_USERNAME=${STROOM_DATAMETA_DB_USERNAME:-datametauser}
      - STROOM_EXPLORER_DB_USERNAME=${STROOM_EXPLORER_DB_USERNAME:-exploreruser}
      - STROOM_PROCESS_DB_USERNAME=${STROOM_PROCESS_DB_USERNAME:-processuser}
      - STROOM_STATS_DB_USERNAME=${STROOM_STATS_DB_USERNAME:-statsuser}
      - STROOM_DB_USERNAME=${STROOM_DB_USERNAME:-stroomuser}

        # Database passwords
      - STROOM_ANNOTATIONS_DB_PASSWORD=${STROOM_ANNOTATIONS_DB_PASSWORD:-stroompassword1}
      - STROOM_AUTH_DB_PASSWORD=${STROOM_AUTH_DB_PASSWORD:-stroompassword1}
      - STROOM_CONFIG_DB_PASSWORD=${STROOM_CONFIG_DB_PASSWORD:-stroompassword1}
      - STROOM_DATAMETA_DB_PASSWORD=${STROOM_DATAMETA_DB_PASSWORD:-stroompassword1}
      - STROOM_EXPLORER_DB_PASSWORD=${STROOM_EXPLORER_DB_PASSWORD:-stroompassword1}
      - STROOM_PROCESS_DB_PASSWORD=${STROOM_PROCESS_DB_PASSWORD:-stroompassword1}
      - STROOM_STATS_DB_PASSWORD=${STROOM_STATS_DB_PASSWORD:-stroompassword1}
      - STROOM_DB_PASSWORD=${STROOM_DB_PASSWORD:-stroompassword1}

    volumes:
      - ${MYSQL_VOLUME_CONF_FILE:-../../volumes/stroom-all-dbs/conf/stroom-all-dbs.cnf}:/etc/mysql/conf.d/stroom-all-dbs.cnf:ro
      - ${MYSQL_VOLUME_INIT:-../../volumes/stroom-all-dbs/init}:/docker-entrypoint-initdb.d:ro
      - type: volume
        source: stroom-all-dbs_data
        target: /var/lib/mysql
      - type: volume
        source: stroom-all-dbs_logs
        target: /var/log/mysql
    logging:
      options:
        max-size: "${MYSQL_STD_OUT_LOGS_MAX_SIZE:-10m}"
        max-file: "${MYSQL_STD_OUT_LOGS_MAX_FILES:-2}"
    labels:
      - "stack_name=${STACK_NAME:-<STACK_NAME>}"
volumes:
  stroom-all-dbs_data:
  stroom-all-dbs_logs:
