version: '2.4'

services:
    
  stroom-log-sender:
    container_name: stroom-log-sender
    image: "${STROOM_LOG_SENDER_DOCKER_REPO:-gchq/stroom-log-sender}:${STROOM_LOG_SENDER_TAG:-local-SNAPSHOT}"
    environment:
      # The url the logs will be sent to
      - DATAFEED_URL=${STROOM_LOG_SENDER_DATAFEED_URL:-https://nginx/stroom/datafeeddirect}
        # The root path of all the logs
      - LOGS_DIR=${STROOM_LOG_SENDER_LOGS_DIR:-/stroom-log-sender/log-volumes}
        # The base path for all stroom logs
      - STROOM_BASE_LOGS_DIR=${STROOM_LOG_SENDER_STROOM_BASE_LOGS_DIR:-${ROOT_LOGS_DIR}/stroom}
        # The base path for all stroom proxy logs
      - STROOM_PROXY_BASE_LOGS_DIR=${STROOM_LOG_SENDER_STROOM_PROXY_BASE_LOGS_DIR:-${ROOT_LOGS_DIR}/stroom-proxy}
        # The base path for all stroom auth service logs
      - STROOM_AUTH_SVC_BASE_LOGS_DIR=${STROOM_LOG_SENDER_STROOM_AUTH_SVC_BASE_LOGS_DIR:-${ROOT_LOGS_DIR}/stroom-auth-service}
        # The base path for all stroom nginx logs
      - STROOM_NGINX_BASE_LOGS_DIR=${STROOM_LOG_SENDER_STROOM_NGINX_BASE_LOGS_DIR:-${ROOT_LOGS_DIR}/stroom-nginx}
        # The default regex used to identify log files ready to send
        # Any '$' symbols must be escaped to '$$'
      - DEFAULT_FILE_REGEX="${STROOM_LOG_SENDER_DEFAULT_FILE_REGEX:-.*/[a-z]+-[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}\.log(\.gz)?$$}"
        # Regex for logrotate dated files, e.g. access.log-20181130-1543576470.gz
      - LOGROTATE_DATED_REGEX="${STROOM_LOG_SENDER_LOGROTATE_DATED_REGEX:-.*/[a-z]+\.log-[0-9]{8}-[0-9]+(\.gz)?}"
        # The environment, e.g. DEV/REF/OPS
      - ENVIRONMENT=${STROOM_LOG_SENDER_ENVIRONMENT:-DEV}
        # The maximum random delay in secs to wait to balance network load
      - MAX_DELAY_SECS=${STROOM_LOG_SENDER_MAX_DELAY_SECS:-15}
        # The PEM format private key
      - PRIVATE_KEY_FILE=${STROOM_LOG_SENDER_PRIVATE_KEY_FILE:-/stroom-log-sender/certs/client.unencrypted.key}
        # The PEM format certificate
      - CERT_FILE=${STROOM_LOG_SENDER_CERT_FILE:-/stroom-log-sender/certs/client.pem.crt}
        # The PEM format CA certificate
      - CA_CERT_FILE=${STROOM_LOG_SENDER_CA_CERT_FILE:-/stroom-log-sender/certs/ca.pem.crt}
    volumes:
      # Volume for the crontab configuration
      - ${STROOM_LOG_SENDER_VOLUME_CONF:-../../volumes/stroom-log-sender/conf}:/stroom-log-sender/config/:ro
      # Volume for the certs/keys
      - ${STROOM_LOG_SENDER_VOLUME_CERTS:-../../volumes/stroom-log-sender/certs}:/stroom-log-sender/certs/:ro

      # A volume for each of the services that this container will ship logs for
      # Mounted as a sub-dir of /stroom-log-sender/log-volumes for consistency
      # Stroom
      - type: volume
        source: stroom_logs
        target: /stroom-log-sender/log-volumes/stroom
      # Stroom Auth
      - type: volume
        source: stroom-auth-service_logs
        target: /stroom-log-sender/log-volumes/stroom-auth-service
      # Stroom Proxy (local)
      - type: volume
        source: stroom-proxy-local_logs
        target: /stroom-log-sender/log-volumes/stroom-proxy
      # Stroom Nginx
      - type: volume
        source: nginx_logs
        target: /stroom-log-sender/log-volumes/stroom-nginx
    logging:
      options:
        max-size: "${STROOM_LOG_SENDER_STD_OUT_LOGS_MAX_SIZE:-10m}"
        max-file: "${STROOM_LOG_SENDER_STD_OUT_LOGS_MAX_FILES:-2}"
    labels:
      - "stack_name=${STACK_NAME:-<STACK_NAME>}"

