version: "2.4"

services:
  stroom-auth-service:
    container_name: stroom-auth-service
    image: "${STROOM_AUTH_SERVICE_DOCKER_REPO:-gchq/stroom-auth-service}:${STROOM_AUTH_SERVICE_TAG:-v7.0-LATEST}"
    environment:
      - ADMIN_CONTEXT_PATH=/authenticationServiceAdmin
      - ADVERTISED_HTTP_HOST=https://${STROOM_AUTH_SERVICE_HOST:-$HOST_IP}
      - ALLOW_PASSWORD_RESETS=${STROOM_AUTH_ALLOW_PASSWORD_RESETS:-false}
      - APPLICATION_CONTEXT_PATH=${STROOM_AUTH_APPLICATION_CONTEXT_PATH:-/}
      - APP_PERMISSIONS_SERVICE_URL=http://${NGINX_ADVERTISED_HOST:-$HOST_IP}/api/appPermissions/v1
      - AUTHORISATION_SERVICE_CAN_MANAGE_USERS_PATH=/canManageUsers
      - AUTHORISATION_SERVICE_CAN_MANAGE_USERS_PERMISSION=Manage Users
      - AUTHORISATION_SERVICE_URL=http://${NGINX_ADVERTISED_HOST:-$HOST_IP}/api/authorisation/v1
      - AUTH_UI=${STROOM_AUTH_UI_ACTIVE_SCHEME:-https}://${STROOM_AUTH_UI_HOST:-$HOST_IP}/s/login
      - CERTIFICATE_DN_CAPTURE_GROUP_INDEX=${STROOM_AUTH_CERTIFICATE_DN_CAPTURE_GROUP_INDEX:-1}
      - CERTIFICATE_DN_PATTERN=${STROOM_AUTH_CERTIFICATE_DN_PATTERN:-.*\((.*)\)}
      - CHANGE_PASSWORD_URL=${STROOM_AUTH_UI_ACTIVE_SCHEME:-https}://${STROOM_AUTH_UI_HOST:-$HOST_IP}/s/changePassword
      - DB_PASSWORD=${STROOM_AUTH_DB_PASSWORD:-stroompassword1}
      - DB_URL=jdbc:mysql://${STROOM_AUTH_DB_HOST:-$DB_HOST_IP}:${STROOM_AUTH_DB_PORT:-3307}/${STROOM_AUTH_DB_NAME:-auth}?useUnicode=yes&characterEncoding=UTF-8
      - DB_USER=${STROOM_AUTH_DB_USERNAME:-authuser}
      - DOCKER_HOST_HOSTNAME=${DOCKER_HOST_HOSTNAME:-UNKNOWN}
      - DOCKER_HOST_IP=${DOCKER_HOST_IP:-UNKNOWN}
      - DURATION_BETWEEN_CHECKS=${STROOM_AUTH_DURATION_BETWEEN_CHECKS:-PT2M}
      - EMAIL_FROM_ADDRESS=${STROOM_AUTH_EMAIL_FROM_ADDRESS:-TODO}
      - EMAIL_FROM_NAME=${STROOM_AUTH_EMAIL_FROM_NAME:-Stroom User Accounts}
      - EMAIL_RESET_SUBJECT=${STROOM_AUTH_EMAIL_RESET_SUBJECT:-Password reset for Stroom}
      - EMAIL_RESET_TEXT=${STROOM_AUTH_EMAIL_RESET_TEXT:-A password reset has been requested for this email address. Please visit the following URL to reset your password -- %s.}
      - EMAIL_RESET_TOKEN_VALIDITY_IN_MINUTES=${STROOM_AUTH_EMAIL_RESET_TOKEN_VALIDITY_IN_MINUTES:-60}
      - EMAIL_RESET_URL=${STROOM_AUTH_UI_ACTIVE_SCHEME:-https}://${STROOM_AUTH_UI_HOST:-$HOST_IP}/s/resetPassword/?token=%s
      - EMAIL_SMTP_HOST=${STROOM_AUTH_EMAIL_SMTP_HOST:-$HOST_IP}
      - EMAIL_SMTP_PASSWORD=${STROOM_AUTH_EMAIL_SMTP_PASSWORD:-} # Must be empty, otherwise the email sender will try to use with a username and password
      - EMAIL_SMTP_PORT=${STROOM_AUTH_EMAIL_SMTP_PORT:-2525}
      - EMAIL_SMTP_TRANSPORT=${STROOM_AUTH_EMAIL_SMTP_TRANSPORT:-plain}
      - EMAIL_SMTP_USERNAME=${STROOM_AUTH_EMAIL_SMTP_USERNAME:-} # Must be empty, otherwise the email sender will try to use with a username and password
      - FAILED_LOGIN_LOCK_THRESHOLD=${STROOM_AUTH_FAILED_LOGIN_LOCK_THRESHOLD:-3}
      - FORCE_PASSWORD_CHANGE_ON_FIRST_LOGIN=${STROOM_AUTH_FORCE_PASSWORD_CHANGE_ON_FIRST_LOGIN:-true}
      - JAVA_OPTS=${STROOM_AUTH_SERVICE_JAVA_OPTS:- -Xms50m -Xmx1024m -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=10769,suspend=n}
      - JWS_ALGORITHM=${STROOM_AUTH_JWS_ALGORITHM:-RS256}
      - JWS_ISSUER=stroom
      - JWS_MINUTES_UNTIL_EXPIRATION_FOR_API_TOKEN=525600 # 525600 minutes = 1 year
      - JWS_MINUTES_UNTIL_EXPIRATION_FOR_EMAIL_RESET_TOKEN=5 # Only 5 minutes
      - JWS_MINUTES_UNTIL_EXPIRATION_FOR_USER_TOKEN=43200 # 43200 minutes = 30 days
      - JWS_REQUIRE_EXPIRATION_TIME=${STROOM_AUTH_JWS_REQUIRE_EXPIRATION_TIME:-false}
      - MANDATORY_PASSWORD_CHANGE_DURATION=${STROOM_AUTH_MANDATORY_PASSWORD_CHANGE_DURATION:-P30D}
      - MINIMUM_PASSWORD_LENGTH=${STROOM_AUTH_MINIMUM_PASSWORD_LENGTH:-8}
      - NEVER_USED_ACCOUNT_DEACTIVATION_THRESHOLD=${STROOM_AUTH_NEVER_USED_ACCOUNT_DEACTIVATION_THRESHOLD:-P30D}
      - OWN_PATH=${STROOM_AUTH_SERVICE:-api/auth/authentication}
      - PASSWORD_COMPLEXITY_REGEX=${STROOM_AUTH_PASSWORD_COMPLEXITY_REGEX:-.*}
      - STROOM_AUTH_SERVICE_ADMIN_PORT=${STROOM_AUTH_SERVICE_ADMIN_PORT:-8100}
      - STROOM_AUTH_SERVICE_PORT=${STROOM_AUTH_SERVICE_PORT:-8099}
      - UNAUTHORISED_URL=${STROOM_AUTH_UI_ACTIVE_SCHEME:-https}://${STROOM_AUTH_UI_HOST:-$HOST_IP}/s/unauthorised
      - UNUSED_ACCOUNT_DEACTIVATION_THRESHOLD=${STROOM_AUTH_UNUSED_ACCOUNT_DEACTIVATION_THRESHOLD:-P90D}
    ports:
      - "${STROOM_AUTH_SERVICE_PORT:-8099}:8099"
      - "${STROOM_AUTH_SERVICE_ADMIN_PORT:-8100}:8100"
      - "${STROOM_AUTH_SERVICE_DEBUG_PORT:-10769}:10769"
    healthcheck:
      test: curl --connect-timeout 5 --max-time 10 --fail --silent --head --output /dev/null http://localhost:${STROOM_AUTH_SERVICE_ADMIN_PORT:-8100}/authenticationServiceAdmin/healthcheck || exit 1
      start_period: 1m
      interval: 1m
      timeout: 5s
      retries: 3
    volumes:
      # TODO: changed this from ro to rw because the stroom-auth-service Dockerfile needs to chown and ro was causing it to fail
      - ${STROOM_AUTH_SERVICE_VOLUME_CONFIG:-../../volumes/stroom-auth-service/config}:/stroom-auth-service/config:rw
      - type: volume
        source: stroom-auth-service_logs
        target: /stroom-auth-service/logs
    logging:
      options:
        max-size: "${STROOM_AUTH_SERVICE_STD_OUT_LOGS_MAX_SIZE:-10m}"
        max-file: "${STROOM_AUTH_SERVICE_STD_OUT_LOGS_MAX_FILES:-2}"
    labels:
      - "stack_name=${STACK_NAME:-<STACK_NAME>}"
